version: '3.7'

networks:
  meetings-app:

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3310:3306
    volumes:
      - ./_data/mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - meetings-app